store/cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
    path('cart_added/', views.cart_added, name='cart_added'),
]

store/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

store/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.CategoryListView.as_view(), name='category-list'),
    path('contacts/', views.contacts, name='contacts'),
    path('about/', views.about, name='about'),
    path('make_an_order/', views.make_order, name='make_order'),
    path('delivery/', views.delivery, name='delivery'),
    path('<slug:slug>/', views.CategoryDetailView.as_view(), name='product-list'),
    path('products/<slug:slug>/', views.ProductDetailView.as_view(), name='product-detail'),

]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
    path('orders/', include('orders.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/cart/models.py
from django.db import models

# Create your models here.

store/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    """Форма для добавления товара в корзину"""
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

store/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product, Category
from .cart import Cart
from .forms import CartAddProductForm



@require_POST
def cart_add(request, product_id):
    """
        Добавление товара в корзину
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=1,
                 update_quantity=cd['update'])
    return redirect('cart:cart_added')


def cart_remove(request, product_id):
    """
        Удаление товара из корзины
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    """
        Отображение корзины
    """
    cart = Cart(request)
    return render(request, 'cart/cart-detail.html', {'cart': cart})


def cart_added(request):
    return render(request, 'cart/cart-added.html')

store/cart/templates/cart/cart-added.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Товар добавлен
{% endblock %}
{% block content %}
    <p>Товар успешно добавлен в корзину!</p>
    <a href="{%url 'cart:cart_detail'%}"><p>Посмотреть корзину..</p></a>
    <a href="{%url 'shop:category-list'%}"><p>Продолжить покупки..</p></a>
{% endblock %}

store/cart/templates/cart/cart-detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
{%if cart|length > 0 %}
    <h1>Ваша корзина</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Изображение</th>
            <th>Товар</th>
            <th>Количество</th>
            <th>Стоимость товара</th>
            <th>Удалить из корзины</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <div class="cart-product">
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="
                                    {% if product.image %}
                                        {{ product.image.url }}
                                    {% else %}
                                        {% static "img/no_image.png" %}
                                    {% endif %}" width="300">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>{{ item.quantity }}</td>
                        <td class="num">₽{{ item.total_price }}</td>
                        <td><a href="{% url 'cart:cart_remove' product.id%}">X</a></td>
                    </tr>
                </div>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Стоимость корзины</td>
            <td colspan="4"></td>
            <td class="num">₽{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'shop:category-list' %}" class="button light">
            В каталог
        </a>
        <a href="{% url 'orders:order_create' %}" class="button">
            Оформить заказ
        </a>
    </p>
{%else%}
<p>Ваша корзина пуста!</p>
{%endif%}
{% endblock %}