store/cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
    path('cart_added/', views.cart_added, name='cart_added'),
]

store/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.CategoryListView.as_view(), name='category-list'),
    path('contacts/', views.contacts, name='contacts'),
    path('about/', views.about, name='about'),
    path('make_an_order/', views.make_order, name='make_order'),
    path('delivery/', views.delivery, name='delivery'),
    path('<slug:slug>/', views.CategoryDetailView.as_view(), name='product-list'),
    path('products/<slug:slug>/', views.ProductDetailView.as_view(), name='product-detail'),

]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
    path('orders/', include('orders.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/shop/models.py
# -*- coding: utf-8 -*-
from django.db import models


class Category(models.Model):
    """
       Модель категории
     """
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название категории")
    slug = models.SlugField(max_length=200, unique=True, db_index=True, verbose_name="Слаг для ссылки")
    image = models.ImageField(upload_to='categories/%Y/%m/%d', blank=True, verbose_name="Изображение категории")

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    """
      Модель товара
    """
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, verbose_name="Категория")
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название товара")
    slug = models.SlugField(max_length=200, db_index=True, verbose_name="Слаг для ссылки")
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name="Изображение товара")
    image1 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name="2 Изображение товара")
    image2 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name="3 Изображение товара")
    description = models.TextField(blank=True, verbose_name="Описание товара")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена товара")
    stock = models.PositiveIntegerField(verbose_name="Количество")
    available = models.BooleanField(default=True, verbose_name="Доступен для продажи")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Создан")
    updated = models.DateTimeField(auto_now=True, verbose_name="Обновлен")
    main_page = models.BooleanField(default=False, verbose_name="Отображается на главной")

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

store/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.views.generic import ListView, DetailView, View
from urllib import request, response
from django.views.generic.edit import FormMixin
from cart.forms import CartAddProductForm


class CategoryListView(ListView):
    """
        Представление списка категорий
    """
    model = Category
    template_name = 'shop/index.html'
    context_object_name = 'category_list'


class CategoryDetailView(DetailView):
    """
        Представление списка товаров одной категории
    """
    model = Category
    template_name = 'shop/product-list.html'
    context_object_name = 'category'

    def get_context_data(self, *args, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(*args, **kwargs)
        context['product_list'] = Product.objects.filter(available=True, category=self.object).order_by('price')
        return context


class ProductDetailView(DetailView, FormMixin):
    """
        Представление товара
    """
    model = Product
    template_name = 'shop/product-detail.html'
    context_object_name = 'product_detail'
    form_class = CartAddProductForm

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        return context


def contacts(request):
    """
        Представление странцы с контактами
    """
    return render(request, 'shop/contacts.html')


def about(request):
    """
        Представление странцы о нас
    """
    return render(request, 'shop/about.html')


def delivery(request):
    """
        Представление странцы доставки
    """
    return render(request, 'shop/delivery.html')


def make_order(request):
    """
        Представление странцы с информацией о персональных заказах
    """
    return render(request, 'shop/make_order.html')

store/shop/templates/shop/about.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    О нас
{% endblock %}
{% block content %}
    О нас
{% endblock %}

store/shop/templates/shop/contacts.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Контакты
{% endblock %}
{% block content %}
    <p>
        <a href="https://vk.com/public180751220"><img src="/media/images/vk.png" alt="VK" height=30px></a>
        <a href="https://vk.com/public180751220"><img src="/media/images/inst.png" alt="Instagramm" height=30px></a>
        <a href=""><img src="/media/images/viber.png" alt="Viber" height=30px></a>
        <a href=""><img src="/media/images/WhatsApp.png" alt="WhatsApp" height=30px></a>
    </p>
{% endblock %}

store/shop/templates/shop/delivery.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Доставка
{% endblock %}
{% block content %}
    Доставляем так-то так-то...
{% endblock %}

store/shop/templates/shop/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Главная
{% endblock %}
{% block content %}
      <p>Товары:</p>
    {%for category in category_list%}
        <p><a href="{%url 'shop:product-list' category.slug%}">{{category.name}}</a></p>
    {%endfor%}
{% endblock %}

store/shop/templates/shop/make_order.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Персональный заказ
{% endblock %}
{% block content %}
    Вы можете сделать персональный заказ украшения из бисера любой сложности...
{% endblock %}

store/shop/templates/shop/product-detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {{object.name}}
{% endblock %}
{% block content %}
    <h1>{{object.name}}</h1>
    <img src="{{ object.image.url }}" alt="{{object.name}}" width="500">
    <p>Описание:</p>
    <p>{{object.description}}</p>
    <p>Цена:</p>
    <p>₽{{object.price}}</p>
    <form action="{% url 'cart:cart_add' object.id %}" method="post">
    {{ form.as_hidden }}
    {% csrf_token %}
    <input type="submit" value="Добавить в корзину">
</form>
{% endblock %}

store/shop/templates/shop/product-list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {{category.name}}
{% endblock %}
{% block content %}
    <h1>{{category.name}}</h1>
    <ul class="products clearfix">
        {%for product in product_list%}
            <li class="product-wrapper">
                <a href="{% url 'shop:product-detail' product.slug %}" class="product">
                    <div class="product-photo">
                        <img src="{{ product.image.url }}">
                    </div>
                 <div class="product-name">{{product.name}}</div>
                <div class="product-price">₽{{product.price}}</div>
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    <div class="product-buttons-wrap">
                        {{ form.as_hidden }}
                        {% csrf_token %}
                        <button type="submit" class = "buttons">Добавить в корзину</button>
                        <button class = "buttons">Подробнее</button>
                    </div>
                </form>
                </a>
            </li>
        {%endfor%}
    </ul>
{% endblock %}